GET localhost:3000

###

POST localhost:3000
Content-Type: application/json
Accept: application/json

{
  "todo": "NodeJS 3"
}

###

PUT localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 0,
  "todo": "NodeJS"
}

###

DELETE localhost:3000
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "todo": "NodeJS"
}

